### ISSUE TITLE
`random.get_int(int limit)` can bias towards small numbers

### ISSUE THREAD

**Issue by alope107** [GValiente/butano#68] opened 2024-05-18 18:07 UTC
This is probably a very minor issue in the context of GBA game development, but maybe worth pointing out.

When calling `random.get_int(int limit)`, if `limit` is not a factor of `numeric_limits<int>::max()` then there will be a bias towards smaller numbers due to [modulo bias](https://research.kudelskisecurity.com/2020/07/28/the-definitive-guide-to-modulo-bias-and-how-to-avoid-it/). There are a couple of ways I can think of to address this:

1. Do not change the implementation, but document this bias.
2. Modify `get_int` to use one of the suggested fixes from the linked article. However, this comes at the cost of worse speed.
3. Have two methods, a biased and unbiased one. Users can use the biased one when speed is more important, and use the unbiased one when a uniform distribution is more important.

In any case, thanks for the great library! I'm having fun with it~

**Comment by GValiente** [comment] 2024-05-18 20:07
Thanks for the issue! I don't think it's so minor for GBA game development, because having unbiased random values is very important in RPGs for example.

However I haven't been able to reproduce the bias shown in the article:
```cpp
    constexpr bool biased = true;
    bn::random random;
    int values[107] = {};

    for(int index = 0; index < 100000; ++index)
    {
        int values_index;

        if(biased)
        {
            values_index = random.get_int(107);
        }
        else
        {
            do
            {
                values_index = random.get_int(256);
            }
            while(values_index >= 107);
        }

        values[values_index] += 1;
    }

    int minimum_index = 0;
    int minimum_value = values[0];
    int maximum_index = 0;
    int maximum_value = values[0];

    for(int index = 0; index < 107; ++index)
    {
        int value = values[index];
        BN_LOG(index, ": ", value);

        if(value < minimum_value)
        {
            minimum_value = value;
            minimum_index = index;
        }

        if(value > maximum_value)
        {
            maximum_value = value;
            maximum_index = index;
        }
    }

    BN_LOG("minimum: ", minimum_index, ": ", minimum_value);
    BN_LOG("maximum: ", maximum_index, ": ", maximum_value);
```

Biased output summary:
```
minimum: 16: 876
maximum: 71: 1042
```

Unbiased output summary:
```
minimum: 67: 864
maximum: 81: 998
```

Unbiased output is a bit better, but not too much IMO.

**Comment by GValiente** [comment] 2024-05-20 00:39
Current unbiased implementation:
```cpp
int random::get_unbiased_int(int limit)
{
    BN_BASIC_ASSERT(limit > 0, "Invalid limit: ", limit);

    // compute the next highest power of 2 of 32-bit
    auto unsigned_limit = unsigned(limit);
    unsigned next_power_of_two = unsigned_limit;
    --next_power_of_two;
    next_power_of_two |= next_power_of_two >> 1;
    next_power_of_two |= next_power_of_two >> 2;
    next_power_of_two |= next_power_of_two >> 4;
    next_power_of_two |= next_power_of_two >> 8;
    next_power_of_two |= next_power_of_two >> 16;
    ++next_power_of_two;

    unsigned and_bits = next_power_of_two - 1;
    unsigned result;

    do
    {
        result = get() & and_bits;
    }
    while(result >= unsigned_limit);

    return int(result);
}
```

And current test code:
```cpp
    template<int size, bool biased>
    void random_test()
    {
        BN_LOG("test: ", size, " - ", biased);

        bn::random random;
        int values[size] = {};
        int its = 100000;

        for(int index = 0; index < its; ++index)
        {
            int values_index;

            if(biased)
            {
                values_index = random.get_int(size);
            }
            else
            {
                values_index = random.get_unbiased_int(size);
            }

            values[values_index] += 1;
        }

        int minimum_index = 0;
        int minimum_value = values[0];
        int maximum_index = 0;
        int maximum_value = values[0];

        for(int index = 0; index < size; ++index)
        {
            int value = values[index];
            // BN_LOG(index, ": ", value);

            if(value < minimum_value)
            {
                minimum_value = value;
                minimum_index = index;
            }

            if(value > maximum_value)
            {
                maximum_value = value;
                maximum_index = index;
            }
        }

        // BN_LOG("minimum: ", minimum_index, ": ", minimum_value);
        // BN_LOG("maximum: ", maximum_index, ": ", maximum_value);

        int diff = maximum_value - minimum_value;
        int average = its / size;
        BN_LOG("diff: ", diff, " - ", bn::fixed(diff * 50) / average, "%");
    }

    // ...

    random_test<2, false>();
    random_test<2, true>();
    random_test<3, false>();
    random_test<3, true>();
    random_test<4, false>();
    random_test<4, true>();
    random_test<5, false>();
    random_test<5, true>();
    random_test<6, false>();
    random_test<6, true>();
    random_test<7, false>();
    random_test<7, true>();
    random_test<107, false>();
    random_test<107, true>();
    random_test<108, false>();
    random_test<108, true>();
```

With it I still don't see enough difference between biased and unbiased implementations (or at least it's not as big as in the linked article):
```
test: 2 - false
diff: 104 - 0.10375%
test: 2 - true
diff: 104 - 0.10375%
test: 3 - false
diff: 109 - 0.16333%
test: 3 - true
diff: 239 - 0.35839%
test: 4 - false
diff: 148 - 0.29589%
test: 4 - true
diff: 148 - 0.29589%
test: 5 - false
diff: 192 - 0.47998%
test: 5 - true
diff: 270 - 0.67480%
test: 6 - false
diff: 184 - 0.55200%
test: 6 - true
diff: 351 - 1.05297%
test: 7 - false
diff: 185 - 0.64746%
test: 7 - true
diff: 211 - 0.73852%
test: 107 - false
diff: 149 - 7.97631%
test: 107 - true
diff: 166 - 8.88647%
test: 108 - false
diff: 149 - 8.05395%
test: 108 - true
diff: 155 - 8.37817%
```

**Comment by alope107** [comment] 2024-05-20 01:50
Ah, I think I get what's going on. In the linked article they use an underlying prng that has a range of [0,255]. With that, 107 is a significant portion and so the large difference in probability is seen. However, the prng in `bn::random` goes all the way up to 2147483647. Because 107 is so relatively small, the modulo bias is also much smaller. To see a larger bias, I think a larger limit than 107 would be needed.

**Comment by alope107** [comment] 2024-05-20 02:04
To check the theory of the higher limits being the problematic ones, I did a quick test of the biased generator with a limit of 901100981:

```
bn::core::init();
auto random = bn::random();

for(int index = 0; index < 10000; ++index)
{
    int values_index;
    values_index = random.get_int(901100981);
    BN_LOG(values_index);
}
```

Then I used script to parse through the mGBA logs and plot a histogram where the samples are put into 100 bins spread across the range:

```
import matplotlib.pyplot as plt
import numpy as np

with open("bnlog.txt", 'r') as f:
    nums = [int(line.strip().split("\t")[-1]) for line in f]

# Define the number of bins (buckets)
num_bins = 100

# Create a histogram with the specified number of bins
counts, bin_edges = np.histogram(nums, bins=num_bins)

# Create the bar chart
plt.figure(figsize=(10, 6))
plt.bar(bin_edges[:-1], counts, width=(bin_edges[1] - bin_edges[0]), edgecolor='black')

# Add labels and title
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.grid(axis='y')

# Show the plot
plt.show()
```

Sure enough, the bias is visible:
![image](https://github.com/GValiente/butano/assets/9411388/2d5142ac-52d8-4fec-a49f-603aa2929852)

**Comment by GValiente** [comment] 2024-05-20 02:06
Can you generate the same plot with the unbiased implementation?

```cpp
int random::get_unbiased_int(int limit)
{
    BN_BASIC_ASSERT(limit > 0, "Invalid limit: ", limit);

    // compute the next highest power of 2 of 32-bit
    auto unsigned_limit = unsigned(limit);
    unsigned next_power_of_two = unsigned_limit;
    --next_power_of_two;
    next_power_of_two |= next_power_of_two >> 1;
    next_power_of_two |= next_power_of_two >> 2;
    next_power_of_two |= next_power_of_two >> 4;
    next_power_of_two |= next_power_of_two >> 8;
    next_power_of_two |= next_power_of_two >> 16;
    ++next_power_of_two;

    unsigned and_bits = next_power_of_two - 1;
    unsigned result;

    do
    {
        result = get() & and_bits;
    }
    while(result >= unsigned_limit);

    return int(result);
}
```

**Comment by alope107** [comment] 2024-05-20 02:12
Looks much better to my eye! If I find some time later I could do some actual statistical tests if you're interested. Also, do you know if there's a way to dump mGBA's logs to a file? I'm just manually copying them right now from mgba-qt.

![image](https://github.com/GValiente/butano/assets/9411388/8940681c-31c6-44f2-aa88-2904f7d0b669)

**Comment by GValiente** [comment] 2024-05-20 02:17
Yeah, it looks better :)

mGBA log can be printed in the standard output, but afaik it can't be stored in a file.

Can you do the same with smaller limits, please? 
Some of the listed prime values above 100: https://en.wikipedia.org/wiki/List_of_prime_numbers

**Comment by alope107** [comment] 2024-05-20 02:21
Sure thing, I'm busy for the rest of today but should be able to find some time tomorrow to automate this analysis a bit better and take a more thorough look.

**Comment by GValiente** [comment] 2024-05-20 02:24
Cool :)

There's no need for it anyway, I'm already working on adding unbiased methods to the random number generators.

**Comment by GValiente** [comment] 2024-05-20 03:32
I've added new methods to the available random number generators to avoid breaking compatibility with old projects: https://github.com/GValiente/butano/commit/1f543cb7fb6edab12d17355a37a58dce29964e30

Since they don't do divisions, in some cases the new methods can be faster than the old ones :)

If you're still in the mood, please check if there's bias with smaller limits.

**Comment by alope107** [comment] 2024-05-20 19:51
Ran a bunch of chi-squared tests for different sizes of limits, only detected anything significant for very large numbers using the old (biased) methods. Looks like the fix works perfectly!

Changes look great. One thing you may consider is documenting the fact that the unbiased versions may update the state of the RNG an unspecified number of times, as this is different from the biased versions. This is a very minor implementation detail but I could imagine it tripping someone up trying to reproduce a bug under very specific circumstances.

Thanks for looking at this; it was a fun little journey.

**Comment by GValiente** [comment] 2024-05-20 19:57
Thanks for the tests!

Seed updates are an implementation detail and they still are deterministic when using the unbiased methods, so I don't think there's need to document that they can be updated multiple times.

I'll close the issue, but feel free to keep commenting on it if you find something interesting.

**Closed by GValiente** 2024-05-20 19:57 UTC
